### ISSUE TITLE
BUG Double-Login

### ISSUE THREAD

**Issue by SebastianZeeb** [SebastianZeeb/cloudchatadvanced#1]
Case 1: Bereits angemeldet mit Username, dann 2. Tab, dann wird der user erneut in die liste geworfen mit selbem username aber anderer SocketID

Case 2: bereits angemeldet mit Username, dann 2. Tab mit URL/chat dann wir dein user mit Username 'null' und neuer SocketID direkt in den Chat gelassen

**Comment by ChristianConrad1** [comment]
gg
